In [ ]:
# datastructure in pandas
# 1-series datastructure
# 2-dataframe datastructure

In [ ]:
# series-one d data structures in pandas is a one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.). The axis labels are collectively referred to as the index. A Series is like a column in a table. You can create a Series by passing a list or array of values to the pandas.Series() constructor.
# dataframe-two d data structures in pandas is a two-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL table, or a dictionary of Series objects. You can create a DataFrame by passing a dictionary of lists or arrays to the pandas.DataFrame() constructor.

In [11]:
# 1.series data structure
import pandas as pd
import numpy as np

In [5]:
# 1 using dictionary
a=pd.Series({'a':10,'b':20,'c':30,'d':40})
print(a)

a    10
b    20
c    30
d    40
dtype: int64

In [6]:
type(a)

pandas.core.series.Series

In [9]:
pd.Series([10,20,30,40],index=['a','b','c','d'])

a    10
b    20
c    30
d    40
dtype: int64

In [14]:
pd.Series(np.arange(10,50))

0     10
1     11
2     12
3     13
4     14
5     15
6     16
7     17
8     18
9     19
10    20
11    21
12    22
13    23
14    24
15    25
16    26
17    27
18    28
19    29
20    30
21    31
22    32
23    33
24    34
25    35
26    36
27    37
28    38
29    39
30    40
31    41
32    42
33    43
34    44
35    45
36    46
37    47
38    48
39    49
dtype: int64

In [15]:
# 1 creting dataframe in pandas

In [16]:
# using dictionary
df=pd.DataFrame({'name':['ajay','vijay','sanjay','rahul'],
                 'age':[25,30,22,28]
})
print(df)

     name  age
0    ajay   25
1   vijay   30
2  sanjay   22
3   rahul   28

In [23]:
df1=pd.DataFrame(np.arange(1,13).reshape(3,4),columns=['col1','col2','col3','col4'])
print(df1)

   col1  col2  col3  col4
0     1     2     3     4
1     5     6     7     8
2     9    10    11    12

In [ ]:
# 12 elements we can possibly have 
#4 rows and 3 columns
#3 rows and 4 columns
#2 rows and 6 columns
#6 rows and 2 columns
#1 row and 12 columns
#12 rows and 1 column

In [24]:
df1=pd.DataFrame(np.arange(1,51).reshape(10,5),columns=['col1','col2','col3','col4','col5'])
print(df1)

   col1  col2  col3  col4  col5
0     1     2     3     4     5
1     6     7     8     9    10
2    11    12    13    14    15
3    16    17    18    19    20
4    21    22    23    24    25
5    26    27    28    29    30
6    31    32    33    34    35
7    36    37    38    39    40
8    41    42    43    44    45
9    46    47    48    49    50

In [25]:
df1

   col1  col2  col3  col4  col5
0     1     2     3     4     5
1     6     7     8     9    10
2    11    12    13    14    15
3    16    17    18    19    20
4    21    22    23    24    25
5    26    27    28    29    30
6    31    32    33    34    35
7    36    37    38    39    40
8    41    42    43    44    45
9    46    47    48    49    50

In [26]:
#aceesing elements in dataframe
df1['col1']

0     1
1     6
2    11
3    16
4    21
5    26
6    31
7    36
8    41
9    46
Name: col1, dtype: int64

In [28]:
df1[['col1','col2']]

   col1  col2
0     1     2
1     6     7
2    11    12
3    16    17
4    21    22
5    26    27
6    31    32
7    36    37
8    41    42
9    46    47

In [ ]:
#Indexing in pandas 
#-accessing individual elements ie-indexing

# slicing in pandas
# we can access a range of elements ie-slicing

In [29]:
df1

   col1  col2  col3  col4  col5
0     1     2     3     4     5
1     6     7     8     9    10
2    11    12    13    14    15
3    16    17    18    19    20
4    21    22    23    24    25
5    26    27    28    29    30
6    31    32    33    34    35
7    36    37    38    39    40
8    41    42    43    44    45
9    46    47    48    49    50

### indexing
 -accessing individual elements
 we are performing indexing using 
 loc and iloc

### indexing using loc 

## loc in indexing  meaning location........we can index elements using label based indexing 
obj.loc[row level,col_level]

In [30]:
df1

   col1  col2  col3  col4  col5
0     1     2     3     4     5
1     6     7     8     9    10
2    11    12    13    14    15
3    16    17    18    19    20
4    21    22    23    24    25
5    26    27    28    29    30
6    31    32    33    34    35
7    36    37    38    39    40
8    41    42    43    44    45
9    46    47    48    49    50

In [31]:
df1.loc[1,'col1']

np.int64(6)

In [32]:
df1.loc[9, 'col5']

np.int64(50)

In [ ]:
df1.loc[-1,'col5'] # we cannnot access using negative indexing in loc

KeyError: -1

## using iloc 
iloc-integer based location 

- obj.iloc[row_index,col_index]

In [36]:
df1

   col1  col2  col3  col4  col5
0     1     2     3     4     5
1     6     7     8     9    10
2    11    12    13    14    15
3    16    17    18    19    20
4    21    22    23    24    25
5    26    27    28    29    30
6    31    32    33    34    35
7    36    37    38    39    40
8    41    42    43    44    45
9    46    47    48    49    50

In [37]:
df1.iloc[2,1]

np.int64(12)

In [38]:
df1.iloc[-1,-1]

np.int64(50)

### slicing in pandas 
- using loc 
- syntax obj.loc[row level slicing,col_level_slicing]

In [39]:
df1

   col1  col2  col3  col4  col5
0     1     2     3     4     5
1     6     7     8     9    10
2    11    12    13    14    15
3    16    17    18    19    20
4    21    22    23    24    25
5    26    27    28    29    30
6    31    32    33    34    35
7    36    37    38    39    40
8    41    42    43    44    45
9    46    47    48    49    50

In [44]:
df1.loc[:1,'col1':'col2']

   col1  col2
0     1     2
1     6     7

In [41]:
df.iloc[0:2, 0:2]

    name  age
0   ajay   25
1  vijay   30

In [42]:
df1.loc[0:1, :'col2']

   col1  col2
0     1     2
1     6     7

In [43]:
df1.loc[0:1, ['col1', 'col2']]

   col1  col2
0     1     2
1     6     7

## slicing using iloc 
- obj.iloc[rowindex_slicing,col_index_slicing]

In [45]:
df1

   col1  col2  col3  col4  col5
0     1     2     3     4     5
1     6     7     8     9    10
2    11    12    13    14    15
3    16    17    18    19    20
4    21    22    23    24    25
5    26    27    28    29    30
6    31    32    33    34    35
7    36    37    38    39    40
8    41    42    43    44    45
9    46    47    48    49    50

In [ ]:
# display the dataframe from first two rows and last two columns

In [52]:
df1.iloc[:2,-2:]

   col4  col5
0     4     5
1     9    10

In [47]:
df1.iloc[:2, 3:5]

   col4  col5
0     4     5
1     9    10

In [48]:
df1.iloc[:2, 3:5]

   col4  col5
0     4     5
1     9    10

In [50]:
df1.iloc[0:2, 3:]

   col4  col5
0     4     5
1     9    10

In [53]:
df1

   col1  col2  col3  col4  col5
0     1     2     3     4     5
1     6     7     8     9    10
2    11    12    13    14    15
3    16    17    18    19    20
4    21    22    23    24    25
5    26    27    28    29    30
6    31    32    33    34    35
7    36    37    38    39    40
8    41    42    43    44    45
9    46    47    48    49    50

In [68]:
print(df1.shape)
print(df1.size)
print(df1.ndim)
print(df1.sample(20, replace=True))

print("-"*50)
print(df1.head(4))
print("-"*50)
print(df1.tail(3))

(10, 5)
50
2
   col1  col2  col3  col4  col5
5    26    27    28    29    30
7    36    37    38    39    40
1     6     7     8     9    10
9    46    47    48    49    50
8    41    42    43    44    45
9    46    47    48    49    50
2    11    12    13    14    15
7    36    37    38    39    40
6    31    32    33    34    35
3    16    17    18    19    20
4    21    22    23    24    25
7    36    37    38    39    40
5    26    27    28    29    30
0     1     2     3     4     5
8    41    42    43    44    45
8    41    42    43    44    45
6    31    32    33    34    35
5    26    27    28    29    30
4    21    22    23    24    25
6    31    32    33    34    35
--------------------------------------------------
   col1  col2  col3  col4  col5
0     1     2     3     4     5
1     6     7     8     9    10
2    11    12    13    14    15
3    16    17    18    19    20
--------------------------------------------------
   col1  col2  col3  col4  col5
7    36    37    38    39    40
8    41    42    43    44    45
9    46    47    48    49    50

In [72]:
print(df1.tail(7))

   col1  col2  col3  col4  col5
3    16    17    18    19    20
4    21    22    23    24    25
5    26    27    28    29    30
6    31    32    33    34    35
7    36    37    38    39    40
8    41    42    43    44    45
9    46    47    48    49    50

In [73]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    10 non-null     int64
 1   col2    10 non-null     int64
 2   col3    10 non-null     int64
 3   col4    10 non-null     int64
 4   col5    10 non-null     int64
dtypes: int64(5)
memory usage: 532.0 bytes

In [75]:
df1['col1'].dtype

dtype('int64')

In [76]:
df1.describe()

            col1       col2       col3       col4       col5
count  10.000000  10.000000  10.000000  10.000000  10.000000
mean   23.500000  24.500000  25.500000  26.500000  27.500000
std    15.138252  15.138252  15.138252  15.138252  15.138252
min     1.000000   2.000000   3.000000   4.000000   5.000000
25%    12.250000  13.250000  14.250000  15.250000  16.250000
50%    23.500000  24.500000  25.500000  26.500000  27.500000
75%    34.750000  35.750000  36.750000  37.750000  38.750000
max    46.000000  47.000000  48.000000  49.000000  50.000000