In [103]:
import numpy as np
    
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [38]:
df=pd.read_csv("train.csv")
df.tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [39]:
df.shape

(891, 12)

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [41]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [42]:
#1 we have understand the data
#2 we have to clean the data
#3 we have to analyse the data

In [43]:
# checking the duplicate values
df.duplicated().sum()

np.int64(0)

In [44]:
# df['Name'].duplicated().sum()
## if you do have duplicate values you can remove by using drop_duplicates() function
df.drop_duplicates(subset=['Name'],inplace=True)

In [45]:
#adding data in my dataframe
# df.loc[len(df)] = [891,0,3,	"Dooley, Mr. Patrick", "male",	32.0,	0,	0,	370376,	7.7500,	None,	"Q"]
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [46]:
## removing null values from the data
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [47]:
# we first fill the null values with mean , median ,mode depending upon the data type
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [48]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [49]:
df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [50]:
df['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [51]:
df['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [52]:
# df.isnull().sum()
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [53]:
#to clean our data we have to fill the null values
# important steps to fill nan value of sour data
# 1..expert suggestion is the most 
#if our data is categorical we use mode to fill the null values
#if our data is numerical we use mean or median to fill the null values

In [54]:
df['Embarked']

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [55]:
df['Embarked'].fillna(df['Embarked'].mode()[0],inplace=True)

In [56]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [57]:
df['Cabin'].head()

0     NaN
1     C85
2     NaN
3    C123
4     NaN
Name: Cabin, dtype: object

In [58]:
df.shape

(891, 12)

In [59]:
#if we have like 80% null values in a column we can drop that column
# before droping that column we must have to inform the team lead or project manager
df['Cabin']=df['Cabin'].fillna('not in cabin! go and check somewhere else')

In [60]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin            0
Embarked         0
dtype: int64

In [61]:
df['Cabin']

0      not in cabin! go and check somewhere else
1                                            C85
2      not in cabin! go and check somewhere else
3                                           C123
4      not in cabin! go and check somewhere else
                         ...
886    not in cabin! go and check somewhere else
887                                          B42
888    not in cabin! go and check somewhere else
889                                         C148
890    not in cabin! go and check somewhere else
Name: Cabin, Length: 891, dtype: object

In [62]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin            0
Embarked         0
dtype: int64

In [63]:
df.sample(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
184,185,1,3,"Kink-Heilmann, Miss. Luise Gretchen",female,4.0,0,2,315153,22.0250,not in cabin! go and check somewhere else,S
422,423,0,3,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.8750,not in cabin! go and check somewhere else,S
688,689,0,3,"Fischer, Mr. Eberhard Thelander",male,18.0,0,0,350036,7.7958,not in cabin! go and check somewhere else,S
548,549,0,3,"Goldsmith, Mr. Frank John",male,33.0,1,1,363291,20.5250,not in cabin! go and check somewhere else,S
82,83,1,3,"McDermott, Miss. Brigdet Delia",female,NaN,0,0,330932,7.7875,not in cabin! go and check somewhere else,Q
347,348,1,3,"Davison, Mrs. Thomas Henry (Mary E Finck)",female,NaN,1,0,386525,16.1000,not in cabin! go and check somewhere else,S
793,794,0,1,"Hoyt, Mr. William Fisher",male,NaN,0,0,PC 17600,30.6958,not in cabin! go and check somewhere else,C
222,223,0,3,"Green, Mr. George Henry",male,51.0,0,0,21440,8.0500,not in cabin! go and check somewhere else,S
370,371,1,1,"Harder, Mr. George Achilles",male,25.0,1,0,11765,55.4417,E50,C
163,164,0,3,"Calic, Mr. Jovo",male,17.0,0,0,315093,8.6625,not in cabin! go and check somewhere else,S

In [64]:
df['Name'].head(20)

0                               Braund, Mr. Owen Harris
1     Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                Heikkinen, Miss. Laina
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                              Allen, Mr. William Henry
5                                      Moran, Mr. James
6                               McCarthy, Mr. Timothy J
7                        Palsson, Master. Gosta Leonard
8     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                   Nasser, Mrs. Nicholas (Adele Achem)
10                      Sandstrom, Miss. Marguerite Rut
11                             Bonnell, Miss. Elizabeth
12                       Saundercock, Mr. William Henry
13                          Andersson, Mr. Anders Johan
14                 Vestrom, Miss. Hulda Amanda Adolfina
15                     Hewlett, Mrs. (Mary D Kingcome)
16                                 Rice, Master. Eugene
17                         Williams, Mr. Charles Eugene
18    Vander Planke, Mrs. Julius (Emelia Maria Vande...
19                              Masselmani, Mrs. Fatima
Name: Name, dtype: object

In [65]:
df[['Name','Age']].head(20)

                                                 Name   Age
0                             Braund, Mr. Owen Harris  22.0
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                              Heikkinen, Miss. Laina  26.0
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                            Allen, Mr. William Henry  35.0
5                                    Moran, Mr. James   NaN
6                             McCarthy, Mr. Timothy J  54.0
7                      Palsson, Master. Gosta Leonard   2.0
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                 Nasser, Mrs. Nicholas (Adele Achem)  14.0
10                    Sandstrom, Miss. Marguerite Rut   4.0
11                           Bonnell, Miss. Elizabeth  58.0
12                     Saundercock, Mr. William Henry  20.0
13                        Andersson, Mr. Anders Johan  39.0
14               Vestrom, Miss. Hulda Amanda Adolfina  14.0
15                   Hewlett, Mrs. (Mary D Kingcome)   55.0
16                               Rice, Master. Eugene   2.0
17                       Williams, Mr. Charles Eugene   NaN
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  31.0
19                            Masselmani, Mrs. Fatima   NaN

In [66]:
#if we do have outliers in our data we can use median to fill the null values
#if we do not have outliers in our data we can use mean to fill the null values

In [67]:
## if we have categorical data we use mode to fill the null values because there could the highest probabilitiesof that null values to be that mode value

In [68]:
# possible steps 
# first get the title from the name column
# based on that title we callculate the mean/median age for that title
#then we fill the null values of age column based on that title mean/median value

In [69]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [70]:
s='Braund, Mr. Owen Harris'
df['Name'].str.split(',').str[1].str.split('.').str[0].str.strip()

0        Mr
1       Mrs
2      Miss
3       Mrs
4        Mr
       ...
886     Rev
887    Miss
888    Miss
889      Mr
890      Mr
Name: Name, Length: 891, dtype: object

In [71]:
s.split(',')

['Braund', ' Mr. Owen Harris']

In [72]:
#to get the title from the name column
#steps
#1.spliting
#2 we retrieve the part after the comma

In [73]:
s

'Braund, Mr. Owen Harris'

In [74]:
a=s.split(',')

In [75]:
b=s.split(',')[1]
b

' Mr. Owen Harris'

In [76]:
c=b.strip()
c

'Mr. Owen Harris'

In [77]:
d=c.split('.')[0]
d

'Mr'

In [78]:
df['Name'].sample(30)

700    Astor, Mrs. John Jacob (Madeleine Talmadge Force)
261                    Asplund, Master. Edvin Rojj Felix
628                            Bostandyeff, Mr. Guentcho
804                              Hedman, Mr. Oskar Arvid
281                     Olsson, Mr. Nils Johan Goransson
668                                      Cook, Mr. Jacob
714                                Greenberg, Mr. Samuel
318                             Wick, Miss. Mary Natalie
344                              Fox, Mr. Stanley Hubert
367                       Moussa, Mrs. (Mantoura Boulos)
345                        Brown, Miss. Amelia "Mildred"
238                      Pengelly, Mr. Frederick William
840                          Alhomaki, Mr. Ilmari Rudolf
712                             Taylor, Mr. Elmer Zebley
536                    Butt, Major. Archibald Willingham
689                    Madill, Miss. Georgette Alexandra
675                       Edvardsson, Mr. Gustaf Hjalmar
251           Strom, Mrs. Wilhelm (Elna Matilda Persson)
393                               Newell, Miss. Marjorie
254             Rosblom, Mrs. Viktor (Helena Wilhelmina)
611                                Jardin, Mr. Jose Neto
444                    Johannesen-Bratthammer, Mr. Bernt
736              Ford, Mrs. Edward (Margaret Ann Watson)
870                                    Balkic, Mr. Cerin
413                       Cunningham, Mr. Alfred Fleming
363                                      Asim, Mr. Adola
676                        Sawyer, Mr. Frederick Charles
296                                   Hanna, Mr. Mansour
849         Goldenberg, Mrs. Samuel L (Edwiga Grabowska)
826                                         Lam, Mr. Len
Name: Name, dtype: object

In [79]:
df['title']=df['Name'].str.split(',').str[1].str.split('.').str[0].str.strip()

In [80]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,not in cabin! go and check somewhere else,S,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,not in cabin! go and check somewhere else,S,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,not in cabin! go and check somewhere else,S,Mr
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,not in cabin! go and check somewhere else,Q,Mr
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,Mr
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,not in cabin! go and check somewhere else,S,Master
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,not in cabin! go and check somewhere else,S,Mrs
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,not in cabin! go and check somewhere else,C,Mrs

In [81]:
mean_age_wrt_title=df.groupby('title')['Age'].mean().round(2)
mean_age_wrt_title

title
Capt            70.00
Col             58.00
Don             40.00
Dr              42.00
Jonkheer        38.00
Lady            48.00
Major           48.50
Master           4.57
Miss            21.77
Mlle            24.00
Mme             24.00
Mr              32.37
Mrs             35.90
Ms              28.00
Rev             43.17
Sir             49.00
the Countess    33.00
Name: Age, dtype: float64

In [82]:
df['Age']=df['Age'].fillna(df['title'].map(mean_age_wrt_title))

In [83]:
df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
title          0
dtype: int64

In [84]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.00,1,0,A/5 21171,7.2500,not in cabin! go and check somewhere else,S,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.00,1,0,PC 17599,71.2833,C85,C,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.00,0,0,STON/O2. 3101282,7.9250,not in cabin! go and check somewhere else,S,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.00,1,0,113803,53.1000,C123,S,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.00,0,0,373450,8.0500,not in cabin! go and check somewhere else,S,Mr
5,6,0,3,"Moran, Mr. James",male,32.37,0,0,330877,8.4583,not in cabin! go and check somewhere else,Q,Mr
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.00,0,0,17463,51.8625,E46,S,Mr
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,not in cabin! go and check somewhere else,S,Master
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.00,0,2,347742,11.1333,not in cabin! go and check somewhere else,S,Mrs
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,237736,30.0708,not in cabin! go and check somewhere else,C,Mrs

In [85]:
df.drop(['title'],axis=1,inplace=True)

In [86]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.00,1,0,A/5 21171,7.2500,not in cabin! go and check somewhere else,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.00,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.00,0,0,STON/O2. 3101282,7.9250,not in cabin! go and check somewhere else,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.00,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.00,0,0,373450,8.0500,not in cabin! go and check somewhere else,S
5,6,0,3,"Moran, Mr. James",male,32.37,0,0,330877,8.4583,not in cabin! go and check somewhere else,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.00,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,not in cabin! go and check somewhere else,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.00,0,2,347742,11.1333,not in cabin! go and check somewhere else,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,237736,30.0708,not in cabin! go and check somewhere else,C

In [87]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.00,1,0,A/5 21171,7.2500,not in cabin! go and check somewhere else,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.00,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.00,0,0,STON/O2. 3101282,7.9250,not in cabin! go and check somewhere else,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.00,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.00,0,0,373450,8.0500,not in cabin! go and check somewhere else,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.00,0,0,211536,13.0000,not in cabin! go and check somewhere else,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.00,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,21.77,1,2,W./C. 6607,23.4500,not in cabin! go and check somewhere else,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.00,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.00,0,0,370376,7.7500,not in cabin! go and check somewhere else,Q

In [88]:
df.drop(columns=['Cabin','PassengerId','Name','Ticket'],inplace=True)

In [89]:
df.head(10)

   Survived  Pclass     Sex    Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.00      1      0   7.2500        S
1         1       1  female  38.00      1      0  71.2833        C
2         1       3  female  26.00      0      0   7.9250        S
3         1       1  female  35.00      1      0  53.1000        S
4         0       3    male  35.00      0      0   8.0500        S
5         0       3    male  32.37      0      0   8.4583        Q
6         0       1    male  54.00      0      0  51.8625        S
7         0       3    male   2.00      3      1  21.0750        S
8         1       3  female  27.00      0      2  11.1333        S
9         1       2  female  14.00      1      0  30.0708        C

In [90]:
#data transformation
df['FamilySize']=df['SibSp']+df['Parch']+1
df.head(10)

   Survived  Pclass     Sex    Age  SibSp  Parch     Fare Embarked  FamilySize
0         0       3    male  22.00      1      0   7.2500        S           2
1         1       1  female  38.00      1      0  71.2833        C           2
2         1       3  female  26.00      0      0   7.9250        S           1
3         1       1  female  35.00      1      0  53.1000        S           2
4         0       3    male  35.00      0      0   8.0500        S           1
5         0       3    male  32.37      0      0   8.4583        Q           1
6         0       1    male  54.00      0      0  51.8625        S           1
7         0       3    male   2.00      3      1  21.0750        S           5
8         1       3  female  27.00      0      2  11.1333        S           3
9         1       2  female  14.00      1      0  30.0708        C           2

In [91]:
df.drop(columns=['SibSp','Parch'],inplace=True)

In [92]:
df.head()

   Survived  Pclass     Sex   Age     Fare Embarked  FamilySize
0         0       3    male  22.0   7.2500        S           2
1         1       1  female  38.0  71.2833        C           2
2         1       3  female  26.0   7.9250        S           1
3         1       1  female  35.0  53.1000        S           2
4         0       3    male  35.0   8.0500        S           1

In [93]:
# 1.label encoding----it should BE USED in target column only
# 2.one hot encoding---for large categorical variable,we donnot use one hot encoding because it increases the dimension of the data
# 3 Target encoding---for features columns

## todo task : implement encoding techniques on categorical columns

In [94]:
df['Sex']=df['Sex'].map({'male':1,'female':0})
df.head()

   Survived  Pclass  Sex   Age     Fare Embarked  FamilySize
0         0       3    1  22.0   7.2500        S           2
1         1       1    0  38.0  71.2833        C           2
2         1       3    0  26.0   7.9250        S           1
3         1       1    0  35.0  53.1000        S           2
4         0       3    1  35.0   8.0500        S           1

In [95]:
df['Embarked']=df['Embarked'].map({'S':0,'C':1,'Q':2})
df.head()

   Survived  Pclass  Sex   Age     Fare  Embarked  FamilySize
0         0       3    1  22.0   7.2500         0           2
1         1       1    0  38.0  71.2833         1           2
2         1       3    0  26.0   7.9250         0           1
3         1       1    0  35.0  53.1000         0           2
4         0       3    1  35.0   8.0500         0           1

In [96]:
X=df.drop('Survived',axis=1)
X.head()

   Pclass  Sex   Age     Fare  Embarked  FamilySize
0       3    1  22.0   7.2500         0           2
1       1    0  38.0  71.2833         1           2
2       3    0  26.0   7.9250         0           1
3       1    0  35.0  53.1000         0           2
4       3    1  35.0   8.0500         0           1

In [99]:
y=df['Survived']
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [ ]:
# from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=40)

In [101]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((712, 6), (179, 6), (712,), (179,))

In [105]:
# from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(X_train,y_train)

LogisticRegression()

In [107]:
lr_pred=lr.predict(X_test)
lr_pred

array([1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1])

In [ ]:
## for the performance metrics
#1.accuracy_score
#2.confusion_matrix
#3.classification_report
#4. precision
#5.recall
#6.f1_score

In [109]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,precision_score,recall_score,f1_score

In [110]:
print("accuracy_score:",accuracy_score(y_test,lr_pred))
print("confusion_matrix:\n",confusion_matrix(y_test,lr_pred))
print("classification_report:\n",classification_report(y_test,lr_pred))
print("precision_score:",precision_score(y_test,lr_pred))
print("recall_score:",recall_score(y_test,lr_pred))
print("f1_score:",f1_score(y_test,lr_pred))

accuracy_score: 0.8156424581005587
confusion_matrix:
 [[87 16]
 [17 59]]
classification_report:
               precision    recall  f1-score   support

           0       0.84      0.84      0.84       103
           1       0.79      0.78      0.78        76

    accuracy                           0.82       179
   macro avg       0.81      0.81      0.81       179
weighted avg       0.82      0.82      0.82       179

precision_score: 0.7866666666666666
recall_score: 0.7763157894736842
f1_score: 0.7814569536423841

In [ ]:
### Accuracy--- out of your total predictions how many predictions are correct
### precision--- out of your total predicted positives how many are actual positives
# --- out of your total survived passanger how many are predicted correctly by your model

### recall---out of your total actual positives how many are predicted correctly by your model

In [122]:
from sklearn.tree import DecisionTreeClassifier,ExtraTreeClassifier

In [120]:
dtc=DecisionTreeClassifier(max_depth=5,criterion='gini')
dtc.fit(X_train,y_train)
dtc_pred=dtc.predict(X_test)
dtc_pred

array([1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1])

In [121]:
print("accuracy_score:",accuracy_score(y_test,dtc_pred))
print("confusion_matrix:\n",confusion_matrix(y_test,dtc_pred))
print("classification_report:\n",classification_report(y_test,dtc_pred))
print("precision_score:",precision_score(y_test,dtc_pred))
print("recall_score:",recall_score(y_test,dtc_pred))
print("f1_score:",f1_score(y_test,dtc_pred))

accuracy_score: 0.8379888268156425
confusion_matrix:
 [[93 10]
 [19 57]]
classification_report:
               precision    recall  f1-score   support

           0       0.83      0.90      0.87       103
           1       0.85      0.75      0.80        76

    accuracy                           0.84       179
   macro avg       0.84      0.83      0.83       179
weighted avg       0.84      0.84      0.84       179

precision_score: 0.8507462686567164
recall_score: 0.75
f1_score: 0.7972027972027972

In [124]:
etc=ExtraTreeClassifier(max_depth=5,criterion='gini')
etc.fit(X_train,y_train)
etc_pred=etc.predict(X_test)
etc_pred

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1])

In [125]:
print("accuracy_score:",accuracy_score(y_test,etc_pred))
print("confusion_matrix:\n",confusion_matrix(y_test,etc_pred))
print("classification_report:\n",classification_report(y_test,etc_pred))
print("precision_score:",precision_score(y_test,etc_pred))
print("recall_score:",recall_score(y_test,etc_pred))
print("f1_score:",f1_score(y_test,etc_pred))

accuracy_score: 0.8212290502793296
confusion_matrix:
 [[100   3]
 [ 29  47]]
classification_report:
               precision    recall  f1-score   support

           0       0.78      0.97      0.86       103
           1       0.94      0.62      0.75        76

    accuracy                           0.82       179
   macro avg       0.86      0.79      0.80       179
weighted avg       0.85      0.82      0.81       179

precision_score: 0.94
recall_score: 0.618421052631579
f1_score: 0.746031746031746